# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve model
#'
#' @param data a List with the model data.
#' @param ufactor a double with an update factor number between (0, 1]. This value is used
#' to update the value of variables at each iteration.
#' @param tol a double with the tolerance criteria.
#' @param maxiter an integer with the number of maximum iterations.
#' @param triter an integer indicating that information should be printed for each
#' multiple of that number.
#' @param trace a boolean indicating whether convergence information should be printed. 
#' @param nthreads an integer indicating the number of threads to use.
#' @export
#' @keywords internal
solve_model <- function(data, ufactor = 0.8, tol = 1e-7, maxiter = 10000L, triter = 100L, trace = TRUE, nthreads = 1L) {
    .Call(`_cp2015_solve_model`, data, ufactor, tol, maxiter, triter, trace, nthreads)
}

